name = "AltInplaceOpsInterface"
uuid = "d59240d3-86bd-48c4-8b44-fa29ea3b0621"
authors = ["bittens "]
version = "0.1.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1"
